"""
PURE V0 App Builder - NO GEMINI, ONLY V0
Based on https://v0.app/docs/api/model

This is the clean, simple, working solution.
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Dict, Optional
import asyncio
import json
from datetime import datetime

from integrations.v0_clean import v0_clean_generator
from integrations.github_api import github_client
from integrations.vercel_api import vercel_client

router = APIRouter()

# Request/Response models
class AppSpec(BaseModel):
    pages: List[str] = ["Home", "Dashboard"]
    theme: Optional[str] = "modern"

class V0BuildRequest(BaseModel):
    project_name: str
    requirements: str
    spec: Optional[AppSpec] = None
    github_repo: Optional[str] = None
    deploy_vercel: bool = True

class V0BuildResponse(BaseModel):
    success: bool
    project_id: str
    message: str
    github_url: Optional[str] = None
    vercel_url: Optional[str] = None
    preview_url: Optional[str] = None
    files_generated: int = 0


def create_sse_event(data: dict) -> str:
    """Create a Server-Sent Event formatted string"""
    return f"data: {json.dumps(data)}\n\n"


@router.post("/mcp/app/build/v0", response_model=V0BuildResponse)
async def build_app_with_v0_only(request: V0BuildRequest):
    """
    Build a complete Next.js app using ONLY V0
    
    NO GEMINI. JUST V0. CLEAN AND SIMPLE.
    """
    
    if not v0_clean_generator:
        raise HTTPException(
            status_code=500,
            detail="V0 API not configured. Set V0_API_KEY environment variable."
        )
    
    project_id = f"v0-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    project_name = request.project_name
    requirements = request.requirements
    
    spec = request.spec or AppSpec()
    pages = spec.pages
    
    try:
        print(f"\n{'='*60}")
        print(f"PURE V0 BUILD STARTED")
        print(f"Project: {project_name}")
        print(f"Requirements: {requirements[:100]}...")
        print(f"{'='*60}\n")
        
        # Step 1: Generate with V0
        print("Step 1: Generating code with V0...")
        
        files = await v0_clean_generator.generate_full_app(
            project_name=project_name,
            user_requirements=requirements,
            pages=pages
        )
        
        if not files:
            raise HTTPException(
                status_code=500,
                detail="V0 failed to generate any files"
            )
        
        print(f"✓ V0 generated {len(files)} files")
        
        # Step 2: Create GitHub repo
        github_url = None
        if github_client:
            try:
                print("\nStep 2: Creating GitHub repository...")
                
                repo_name = project_name.lower().replace(' ', '-').replace('_', '-')
                repo_result = await github_client.create_repo(
                    name=repo_name,
                    description=f"Generated by OPS-X with V0: {requirements[:100]}",
                    private=False
                )
                
                print(f"GitHub create_repo result: {repo_result}")
                
                if repo_result.get("success"):
                    github_url = repo_result.get("repo_url")
                    repo_full_name = repo_result.get("repo_name")  # This is username/repo
                    print(f"✓ GitHub repo created: {github_url}")
                    
                    # Push files to repo
                    print("Pushing files to GitHub...")
                    
                    push_result = await github_client.push_multiple_files(
                        repo_full_name=repo_full_name,
                        files=files,
                        commit_message=f"Initial commit: {project_name} (generated by V0)"
                    )
                    
                    if push_result.get("success"):
                        print(f"✓ Pushed {len(files)} files to GitHub")
                    else:
                        print(f"⚠ GitHub push failed: {push_result.get('error')}")
                else:
                    print(f"⚠ GitHub repo creation failed: {repo_result.get('error')}")
            
            except Exception as e:
                print(f"⚠ GitHub integration failed: {e}")
        
        # Step 3: Deploy to Vercel
        vercel_url = None
        if request.deploy_vercel and vercel_client and github_url:
            try:
                print("\nStep 3: Deploying to Vercel...")
                
                deploy_result = await vercel_client.create_project(
                    name=repo_name,
                    git_url=github_url
                )
                
                if deploy_result.get("success"):
                    vercel_url = deploy_result.get("url")
                    print(f"✓ Deployed to Vercel: {vercel_url}")
                else:
                    print(f"⚠ Vercel deployment failed: {deploy_result.get('error')}")
            
            except Exception as e:
                print(f"⚠ Vercel deployment failed: {e}")
        
        print(f"\n{'='*60}")
        print(f"PURE V0 BUILD COMPLETE")
        print(f"✓ Files: {len(files)}")
        print(f"✓ GitHub: {github_url or 'N/A'}")
        print(f"✓ Vercel: {vercel_url or 'N/A'}")
        print(f"{'='*60}\n")
        
        return V0BuildResponse(
            success=True,
            project_id=project_id,
            message=f"Successfully built {project_name} with V0!",
            github_url=github_url,
            vercel_url=vercel_url,
            files_generated=len(files)
        )
    
    except Exception as e:
        print(f"\n✗ BUILD FAILED: {e}\n")
        raise HTTPException(
            status_code=500,
            detail=f"Build failed: {str(e)}"
        )


@router.post("/mcp/app/build/v0/stream")
async def build_app_with_v0_streaming(request: V0BuildRequest):
    """
    Build app with V0 and stream progress updates
    """
    
    if not v0_clean_generator:
        raise HTTPException(
            status_code=500,
            detail="V0 API not configured"
        )
    
    async def event_generator():
        """Generate SSE events for build progress"""
        
        project_id = f"v0-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        
        try:
            # Start
            yield create_sse_event({
                "type": "status",
                "phase": "started",
                "message": f"Starting V0 build for {request.project_name}...",
                "progress": 0
            })
            
            await asyncio.sleep(0.5)
            
            # V0 Generation
            yield create_sse_event({
                "type": "status",
                "phase": "generating",
                "message": "Generating code with V0...",
                "progress": 10
            })
            
            all_files = {}
            
            # Stream callback for V0 progress
            async def v0_progress_callback(chunk: str, accumulated: str):
                yield create_sse_event({
                    "type": "v0_progress",
                    "chunk": chunk,
                    "progress": min(10 + len(accumulated) // 100, 80)
                })
            
            files = await v0_clean_generator.generate_full_app(
                project_name=request.project_name,
                user_requirements=request.requirements,
                pages=request.spec.pages if request.spec else ["Home"]
            )
            
            all_files.update(files)
            
            yield create_sse_event({
                "type": "status",
                "phase": "generated",
                "message": f"V0 generated {len(files)} files!",
                "progress": 85,
                "files": list(files.keys())
            })
            
            # Generate preview HTML
            preview_html = generate_v0_preview_html(all_files, request.project_name)
            yield create_sse_event({
                "type": "preview_ready",
                "html": preview_html,
                "progress": 87
            })
            
            # GitHub + Vercel (if requested)
            github_url = None
            if github_client and request.deploy_vercel:
                yield create_sse_event({
                    "type": "status",
                    "phase": "github",
                    "message": "Creating GitHub repository...",
                    "progress": 90
                })
                
                try:
                    repo_name = request.project_name.lower().replace(' ', '-').replace('_', '-')
                    repo_result = await github_client.create_repo(
                        name=repo_name,
                        description=f"Generated by OPS-X with V0: {request.requirements[:100]}",
                        private=False
                    )
                    
                    if repo_result.get("success"):
                        github_url = repo_result.get("repo_url")
                        repo_full_name = repo_result.get("repo_name")
                        
                        yield create_sse_event({
                            "type": "status",
                            "phase": "github_created",
                            "message": f"Repository created: {github_url}",
                            "progress": 92,
                            "github_url": github_url
                        })
                        
                        # Push files
                        yield create_sse_event({
                            "type": "status",
                            "phase": "github_push",
                            "message": "Pushing files to GitHub...",
                            "progress": 93
                        })
                        
                        push_result = await github_client.push_multiple_files(
                            repo_full_name=repo_full_name,
                            files=all_files,
                            commit_message=f"Initial commit: {request.project_name} (generated by V0)"
                        )
                        
                        if push_result.get("success"):
                            yield create_sse_event({
                                "type": "status",
                                "phase": "github_pushed",
                                "message": f"Pushed {len(all_files)} files to GitHub!",
                                "progress": 95
                            })
                        else:
                            yield create_sse_event({
                                "type": "status",
                                "phase": "github_push_failed",
                                "message": f"Warning: GitHub push failed",
                                "progress": 95
                            })
                    else:
                        yield create_sse_event({
                            "type": "status",
                            "phase": "github_failed",
                            "message": "Warning: GitHub repo creation failed",
                            "progress": 95
                        })
                except Exception as gh_error:
                    yield create_sse_event({
                        "type": "status",
                        "phase": "github_error",
                        "message": f"GitHub error: {str(gh_error)}",
                        "progress": 95
                    })
            
            # Complete
            yield create_sse_event({
                "type": "complete",
                "phase": "done",
                "message": "Build complete!",
                "progress": 100,
                "project_id": project_id,
                "files_count": len(all_files)
            })
        
        except Exception as e:
            yield create_sse_event({
                "type": "error",
                "phase": "failed",
                "message": str(e),
                "error": str(e)
            })
    
    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


def generate_v0_preview_html(files: Dict[str, str], project_name: str) -> str:
    """
    Generate ACTUAL RENDERED preview from V0-generated files
    Try to render the React component, not just list files
    """
    
    # Find the main page file
    page_tsx = files.get("app/page.tsx") or files.get("src/app/page.tsx") or files.get("app/page.jsx", "")
    globals_css = files.get("app/globals.css") or files.get("src/app/globals.css", "")
    
    if not page_tsx:
        # No page found, show simple status
        return f"""
<!DOCTYPE html>
<html>
<head>
    <title>{project_name}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-gradient-to-br from-gray-900 to-black text-white p-8">
    <div class="max-w-4xl mx-auto text-center">
        <div class="inline-block bg-green-500 px-4 py-1 rounded-full text-sm mb-4">V0 Generated</div>
        <h1 class="text-4xl font-bold">{project_name}</h1>
        <p class="text-gray-400 mt-2">Generated {len(files)} files</p>
    </div>
</body>
</html>
"""
    
    # V0 generates React components - try to render them in browser
    # Extract the component and render it with React CDN + Tailwind
    
    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name} - Live Preview</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lucide-react@latest/dist/umd/lucide-react.min.js"></script>
    <style>
        {globals_css}
        
        /* Additional V0 compatible styles */
        * {{
            box-sizing: border-box;
        }}
        body {{
            margin: 0;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }}
    </style>
</head>
<body>
    <div id="root"></div>
    
    <script type="text/babel">
        // V0-generated component code
        {page_tsx.replace('export default', 'const App =')}
        
        // Render the app
        const root = ReactDOM.createRoot(document.getElementById('root'));
        root.render(<App />);
    </script>
    
    <script>
        // Handle errors gracefully
        window.onerror = function(msg, url, lineNo, columnNo, error) {{
            console.error('Preview error:', msg, error);
            document.getElementById('root').innerHTML = `
                <div style="padding: 40px; text-align: center; font-family: system-ui;">
                    <div style="display: inline-block; background: #10b981; color: white; padding: 8px 16px; border-radius: 20px; font-size: 14px; margin-bottom: 20px;">V0 Generated</div>
                    <h1 style="font-size: 2.5em; margin: 10px 0;">{project_name}</h1>
                    <p style="color: #666; margin-bottom: 30px;">Generated {len(files)} files</p>
                    <div style="background: #f5f5f5; border-radius: 12px; padding: 30px; max-width: 600px; margin: 0 auto;">
                        <h2 style="color: #10b981; margin: 0 0 15px 0;">✓ Code Generated Successfully</h2>
                        <p style="color: #333; margin-bottom: 15px;">V0 has generated your Next.js application!</p>
                        <div style="text-align: left; font-size: 14px; color: #666;">
                            {"".join([f'<div style="padding: 5px 0;">✓ {fname}</div>' for fname in sorted(files.keys())])}
                        </div>
                    </div>
                    <p style="color: #999; margin-top: 30px; font-size: 14px;">Deploying to GitHub and Vercel...</p>
                </div>
            `;
            return true;
        }};
    </script>
</body>
</html>
"""


# Health check
@router.get("/mcp/app/build/v0/health")
async def v0_health_check():
    """Check if V0 integration is working"""
    return {
        "status": "healthy" if v0_clean_generator else "v0_not_configured",
        "generator": "v0-1.5-md",
        "docs": "https://v0.app/docs/api/model"
    }

